name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository with a fetch depth of 2
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 2

      # Use the StackSpotAI-CICD action to run a remote quick command for Markdown files
      - uses: victorsilvazup/stackspot-ai-execute-rqc@main
        id: rqc_md
        with:
          CLIENT_ID: ${{ secrets.STK_CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.STK_CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.STK_CLIENT_REALM }}
          QC_SLUG: code-analysis
          FILE_EXTENSION: .md      

      # Use the StackSpotAI-CICD action to run a remote quick command for YAML files
      - uses: victorsilvazup/stackspot-ai-execute-rqc@main
        id: rqc_yml
        with:
          CLIENT_ID: ${{ secrets.STK_CLIENT_ID }}
          CLIENT_KEY: ${{ secrets.STK_CLIENT_KEY }}
          CLIENT_REALM: ${{ secrets.STK_CLIENT_REALM }}
          QC_SLUG: code-analysis
          FILE_EXTENSION: .yml

      # Install jq
      - name: Install jq
        run: sudo apt-get install -y jq

      # Check the raw result of the Remote Quick Command for Markdown files
      - name: Output Raw Remote Quick Command Result for Markdown
        run: echo "${{ steps.rqc_md.outputs.rqc_result }}"

      # Check the raw result of the Remote Quick Command for YAML files
      - name: Output Raw Remote Quick Command Result for YAML
        run: echo "${{ steps.rqc_yml.outputs.rqc_result }}"

      # Check the result of the Remote Quick Command for Markdown files
      - name: Check Remote Quick Command answer for Markdown
        run: echo "${{ steps.rqc_md.outputs.rqc_result }}" | jq .

      # Check the result of the Remote Quick Command for YAML files
      - name: Check Remote Quick Command answer for YAML
        run: echo "${{ steps.rqc_yml.outputs.rqc_result }}" | jq .
