name: Print JSON on Command

on:
  workflow_dispatch:

jobs:
  print-json:
    runs-on: ubuntu-latest
    steps:
      - name: Print JSON
        run: |
          printf '{\n\n  "name": "StackSpot",\n  "type": "AI Assistant",\n  "features": ["code generation", "code review", "debugging"]\n}\n'