steps:
    - uses: actions/checkout@v4
      with: 
          fetch-depth: 2 # mandatory to detect changes in files

    - uses: victorsilvazup/stackspot-ai-execute-rqc@v1
      id: rqc
      with:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
        CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
        QC_SLUG: lfv-test-rqc #YOUR_REMOTE_QUICK_COMMAND_SLUG
        FILE_EXTENSION: remote-qc.yml #YOUR_FILE_EXTENSION

    - name: Check Remote Quick Command answer
      run: echo ${{ toJSON(steps.rqc.outputs.rqc_result) }}